#!/bin/bash

cd libvirus
	make clean
	rm -Rf CMakeCache.txt CMakeFiles cmake_install.cmake libvirus-exports.cmake Makefile
	cd ..

cd libvirustest
	make clean
	rm -Rf CMakeCache.txt CMakeFiles cmake_install.cmake libvirustest-exports.cmake Makefile
	cd ..

cd virustest
	make clean
	rm -Rf CMakeCache.txt CMakeFiles cmake_install.cmake Makefile
	cd ..

